default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: nazar

development:
  <<: *default
  database: studdev_dev

test:
  <<: *default
  database: studdev_test

production:
  <<: *default
  database: studdev_prod
